Fix: Add missing includes to fix compilation errors
Fixed compilation errors in UiAutoPlay.cpp:
- error C2065: 'c2s_autosortequipment' : undeclared identifier
- error C2065: 'g_pClient' : undeclared identifier

ADDED INCLUDES:
- #include "../../../Headers/KProtocolDef.h" for c2s_autosortequipment constant
- #include "../../../core/src/KCore.h" for g_pClient extern declaration

REMOVED:
- Local "extern iClientConnectServer* g_pClient;" (wrong type, g_pClient is IClient*)
- Now using global g_pClient from KCore.h

This fixes all 5 compilation errors reported by user.